version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    networks:
      - payment-network

  fraud-service:
    build: ./fraud-service
    ports:
      - "8083:8083"
    networks:
      - payment-network

  transaction-service:
    build: ./transaction-service
    ports:
      - "8082:8082"
    depends_on:
      - auth-service
      - fraud-service
    environment:
      - FRAUD_SERVICE_URL=http://fraud-service:8083/fraud/check
    networks:
      - payment-network

networks:
  payment-network:
    driver: bridge
